const constants = {
  ENTER_USERNAME: 'ENTER_USERNAME',
  ENTER_PASSWORD: 'ENTER_PASSWORD',
  LOGIN: 'LOGIN',
  ENTER_SONG: 'ENTER_SONG',
  SUBMIT_SONG: 'SUBMIT_SONG',
  CLICK_HISTORY: 'CLICK_HISTORY'
}

export default constants;